const fs = require('fs');
const path = require('path');
const { UPLOAD_DIR } = require('../config/environment');

const generateReportFile = async (patient, bill, test, findings, author) => {
  try {
    const baseDir = process.env.VERCEL
      ? '/tmp/uploads'
      : path.resolve(__dirname, '../../', UPLOAD_DIR);

    const reportDir = path.join(baseDir, 'reports');
    if (!fs.existsSync(reportDir)) {
      fs.mkdirSync(reportDir, { recursive: true });
    }

    const filename = `report_${bill.billNumber}_${Date.now()}.txt`;
    const filepath = path.join(reportDir, filename);

    const content = `
============================================================
                     PURE PATH LAB
         Pathology and Laboratory Diagnosis Center
============================================================
Patient Name      : ${patient.name}
Age / Gender      : ${patient.age} / ${patient.gender}
Reg Number        : ${patient.registrationNumber}
Bill Number       : ${bill.billNumber}
Date              : ${new Date().toLocaleString()}
Referred By       : ${bill.referringDoctor ? bill.referringDoctor.name : 'Self'}
============================================================
TEST: ${test.name} (${test.code})
============================================================
RESULT VALUE      : ${findings.value || 'N/A'} ${test.unit || ''}
NORMAL RANGE      : ${test.referenceRange || 'N/A'}
(M: ${test.maleReferenceRange || 'N/A'}, F: ${test.femaleReferenceRange || 'N/A'})

FINDINGS DETAILS  : 
${findings.description || 'No additional comments.'}

INTERPRETATION    : 
${test.interpretation || 'No interpretation text on file.'}
============================================================
Generated By      : ${author.name}
Sign-off Status   : AUTHORIZED SIGNATORY (PURE PATH LAB)
============================================================
    `;

    fs.writeFileSync(filepath, content.trim());
    return `${UPLOAD_DIR}/reports/${filename}`;
  } catch (error) {
    console.error('Failed to write clinical report text file', error);
    throw error;
  }
};

module.exports = {
  generateReportFile
};
